### PR TITLE
various fixes + cleanups

### PR DESCRIPTION
**Pull request by jab**

### CODE REVIEW

**Comment by lowks** [comment]
Great ! Thanks @jab !

**Comment by jab** [comment]
sure thing :)

**Comment by lowks** [comment]
I know this is after the fact but why don't we need a manifest anymore @jab ?

**Comment by jab** [comment]
The manifest was a vestige of when there used to be a docs directory (you can tell because its contents were only `recursive-include docs *`). The docs directory was removed in 64f0a8ea07639e23aea41593d14f5b7d8362813e (and the files inside it were moved into the root directory), so the manifest was referencing a directory that no longer exists.

I just added a new manifest in 78c8c09adae430cee572376cf8b653a488b5ff36 that includes the files that used to be in the docs directory (now in the root directory). They're not strictly necessary to create a minimock distribution that can be successfully installed from, but they're nice to include anyway.

I also cleaned up the test setup. There's no need to use nose or a dedicated `test` shell script just to run the doctests inside minimock.py; `python -m doctest minimock.py` is all you need to run the doctests in minimock.py.

**Comment by lowks** [comment]
Okay. Thanks

**Comment by jab** [comment]
sure thing

**Pull request merged**
